default:
    path: /
    controller: App\Controller\defaultController:displaySelection

vet:
  path: vet
  controller: App\Controller\weterynarz::list

animal:
  path: vet/{num}/details
  controller: App\Controller\weterynarz::details
  defaults:
      num: 1
  requirements:
      num: '\d+'

owner: 
    path: owner
    controller: App\Controller\klienci::list

ownerDetails: 
    path: owner/{num}
    controller: App\Controller\klienci::details
    defaults:
        num: 1
    requirements:
        num: '\d+'

animalDetails:
    path: animal/{num}
    controller: App\Controller\klienci::animal
    defaults:
        num: 1
    requirements:
        num: '\d+'    