default:
    path: /
    controller: App\Controller\defaultController:displaySelection

vet:
  path: vet
  controller: App\Controller\weterynarz::displayVet

animal:
  path: vet/{vetNum}/details
  controller: App\Controller\weterynarz::displayVetDetails
  defaults:
      vetNum: 1
  requirements:
      vetNum: '\d+'

owner: 
    path: owner
    controller: App\Controller\weterynarz::displayOwner

ownerDetails: 
    path: owner/{ownNum}
    controller: App\Controller\weterynarz::displayOwnerDetails
    defaults:
        ownNum: 1
    requirements:
        ownNum: '\d+'

animalDetails:
    path: animal/{aniNum}
    controller: App\Controller\weterynarz::displayAnimalDetails
    defaults:
        aniNum: 1
    requirements:
        aniNum: '\d+'    